apiVersion: v1
kind: Secret
metadata:
  name: account-service-secrets
  namespace: finance-services-dev
  labels:
    app: account-service
    environment: development
type: Opaque
data:
  # Base64 encoded values for development environment
  # Note: These are development secrets and should be replaced with proper secret management
  SPRING_DATASOURCE_PASSWORD: cG9zdGdyZXM=  # postgres
  JWT_SECRET: ZGV2LWp3dC1zZWNyZXQtdGhhdC1zaG91bGQtYmUtcmVwbGFjZWQtaW4tcHJvZHVjdGlvbg==  # dev-jwt-secret-that-should-be-replaced-in-production
  DATABASE_PASSWORD: cG9zdGdyZXM=  # postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secrets
  namespace: finance-services-dev
  labels:
    app: postgres
    environment: development
type: Opaque
data:
  # Base64 encoded values for PostgreSQL
  POSTGRES_PASSWORD: cG9zdGdyZXM=  # postgres
  POSTGRES_ROOT_PASSWORD: cG9zdGdyZXM=  # postgres

---
# Service Account for the application
apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-service-sa
  namespace: finance-services-dev
  labels:
    app: account-service
    environment: development
automountServiceAccountToken: true

---
# Role for the service account with minimal permissions
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: finance-services-dev
  name: account-service-role
  labels:
    app: account-service
    environment: development
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list"]

---
# Role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: account-service-rolebinding
  namespace: finance-services-dev
  labels:
    app: account-service
    environment: development
subjects:
- kind: ServiceAccount
  name: account-service-sa
  namespace: finance-services-dev
roleRef:
  kind: Role
  name: account-service-role
  apiGroup: rbac.authorization.k8s.io