apiVersion: v1
kind: ServiceAccount
metadata:
  name: account-service-sa
  namespace: finance-services
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: finance-services
  name: account-service-role
rules:
- apiGroups: [""]
  resources: ["configmaps", "secrets"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: account-service-rolebinding
  namespace: finance-services
subjects:
- kind: ServiceAccount
  name: account-service-sa
  namespace: finance-services
roleRef:
  kind: Role
  name: account-service-role
  apiGroup: rbac.authorization.k8s.io