package com.suhasan.finance.transaction_service.ledger.domain;

public enum ReconciliationCheckCode {
    JOURNAL_BALANCE_BY_CURRENCY,
    JOURNAL_CURRENCY_CONSISTENCY,
    LIFECYCLE_TRANSITION,
    PROJECTION_RECOMPUTATION,
    MIRROR_DRIFT,
    MISSING_AUDIT_LINKAGE,
    STALE_PENDING_JOURNAL,
    FAILED_COMPENSATION,
    NON_ZERO_SUSPENSE,
    MISSING_SYSTEM_ACCOUNT,
    STATEMENT_CLOSING_BALANCE
}
