global:
  resolve_timeout: 5m

route:
  receiver: local-certification-receiver
  group_by: [alertname, service, severity]
  group_wait: 10s
  group_interval: 1m
  repeat_interval: 1h
  routes:
    - matchers: [severity="critical"]
      receiver: local-certification-receiver
      group_wait: 0s
      repeat_interval: 15m

receivers:
  - name: local-certification-receiver
    webhook_configs:
      - url: http://alert-certification-receiver:8080/alerts
        send_resolved: true

inhibit_rules:
  - source_matchers: [severity="critical"]
    target_matchers: [severity="warning"]
    equal: [service, component]
