package com.suhasan.finance.account_service.entity;

public enum NotificationType {
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,
    ACCOUNT_FROZEN,
    ACCOUNT_UNFROZEN,
    DISPUTE_CREATED,
    DISPUTE_STATUS_UPDATED,
    SCHEDULED_TRANSFER_CREATED,
    SCHEDULED_TRANSFER_EXECUTED,
    SCHEDULED_TRANSFER_FAILED,
    SCHEDULED_TRANSFER_PAUSED,
    SCHEDULED_TRANSFER_RESUMED,
    SCHEDULED_TRANSFER_CANCELED
}
