package com.suhasan.finance.account_service.entity;

public enum NotificationType {
    TRANSACTION_COMPLETED,
    TRANSACTION_FAILED,
    ACCOUNT_FROZEN,
    ACCOUNT_UNFROZEN,
    DISPUTE_CREATED,
    DISPUTE_STATUS_UPDATED,
    SCHEDULED_TRANSFER_CREATED,
    SCHEDULED_TRANSFER_EXECUTED,
    SCHEDULED_TRANSFER_FAILED,
    SCHEDULED_TRANSFER_PAUSED,
    SCHEDULED_TRANSFER_RESUMED,
    SCHEDULED_TRANSFER_CANCELED,
    OUTCOME_PROTECTION_AT_RISK,
    BALANCE_SHIELD_CONSENT_PENDING,
    BALANCE_SHIELD_ACTIVATED,
    BALANCE_SHIELD_SUSPENDED,
    BALANCE_SHIELD_RESUMED,
    BALANCE_SHIELD_REVOKED,
    BALANCE_SHIELD_ACTION_REQUIRES_MFA,
    BALANCE_SHIELD_ACTION_COMPLETED,
    BALANCE_SHIELD_ACTION_FAILED,
    SECURITY_ACTION_REQUIRED,
    SECURITY_ALERT,
    TRANSFER_AUTHORIZED
}
