global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert_rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Account Service Application
  - job_name: 'account-service'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s
    
  # PostgreSQL Database Metrics
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    
  # Redis Metrics (if enabled)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    
  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Node Exporter for System Metrics (if available)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # JVM Metrics from Spring Boot Actuator
  - job_name: 'jvm-metrics'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/actuator/prometheus'
    params:
      match[]: ['{__name__=~"jvm_.*"}']
    scrape_interval: 15s

  # Custom Business Metrics
  - job_name: 'business-metrics'
    static_configs:
      - targets: ['app:8080']
    metrics_path: '/actuator/prometheus'
    params:
      match[]: ['{__name__=~"account_.*|transaction_.*|auth_.*"}']
    scrape_interval: 10s