-- Core schema for account-service.

CREATE SEQUENCE IF NOT EXISTS roles_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE IF NOT EXISTS users_seq START WITH 1 INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS roles (
    id BIGINT PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS users (
    id BIGINT PRIMARY KEY,
    username VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL
);

CREATE TABLE IF NOT EXISTS user_roles (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (role_id, user_id),
    CONSTRAINT fk_user_roles_user
        FOREIGN KEY (user_id) REFERENCES users (id),
    CONSTRAINT fk_user_roles_role
        FOREIGN KEY (role_id) REFERENCES roles (id)
);

CREATE TABLE IF NOT EXISTS accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version BIGINT NOT NULL,
    owner_id VARCHAR(255) NOT NULL,
    balance NUMERIC(38,2) NOT NULL,
    created_at DATE NOT NULL,
    account_type VARCHAR(31) NOT NULL,
    interest_rate DOUBLE PRECISION,
    credit_limit NUMERIC(38,2),
    due_date DATE
);

CREATE INDEX IF NOT EXISTS idx_accounts_owner_id ON accounts (owner_id);
CREATE INDEX IF NOT EXISTS idx_accounts_type ON accounts (account_type);
