// API types, derived from the OpenAPI specs (docs/api/*.openapi.json, generated into
// src/api/generated by `npm run api:types`). A server-side rename, removal or type change
// breaks the build instead of the screen. Only Page<T>, Spring's generic page envelope, is
// written by hand.
import type { components as AccountApi } from "./api/generated/account-service";
import type { components as TransactionApi } from "./api/generated/transaction-service";

type AccountSchemas = AccountApi["schemas"];
type TransactionSchemas = TransactionApi["schemas"];

/**
 * A response type derived from an OpenAPI schema. springdoc marks every response field
 * optional, so `Req` lists the fields the UI relies on (made required and non-null), and
 * `Over` narrows or nests selected fields. Field names and types come from the spec: a field
 * renamed or retyped on the server breaks the build instead of the screen.
 */
type FromApi<S, Req extends keyof S = never, Over extends object = Record<never, never>> =
  Omit<S, Req | keyof Over> & { [K in Exclude<Req, keyof Over>]-?: NonNullable<S[K]> } & Over;

/** Narrowed fields must exist in the spec; an unknown name becomes a string the build rejects. */
type Known<S, O> = Exclude<keyof O, keyof S> extends never
  ? O
  : `field not in the API spec: ${Exclude<keyof O, keyof S> & string}`;

/** RFC 9457 Problem Details, the error body of every API endpoint. */
export type ApiProblem = AccountSchemas["Problem"];

export type Role = "ROLE_USER" | "ROLE_ADMIN" | "ROLE_INTERNAL_SERVICE" | string;

export type Page<T> = {
  content: T[];
  number: number;
  size: number;
  totalElements: number;
  totalPages: number;
  first: boolean;
  last: boolean;
};

export type AccountType = "CHECKING" | "SAVINGS" | "CREDIT";
export type AccountStatus = NonNullable<AccountSchemas["AccountResponse"]["status"]>;

export type Account = FromApi<AccountSchemas["AccountResponse"], "id" | "ownerId" | "balance" | "createdAt", Known<AccountSchemas["AccountResponse"], {
  accountType: AccountType,
  currency: "USD" | "EUR" | "GBP" | "INR"
}>>;

export type BeneficiaryStatus = NonNullable<AccountSchemas["BeneficiaryResponse"]["status"]>;

export type Beneficiary = FromApi<AccountSchemas["BeneficiaryResponse"], "beneficiaryId" | "userId" | "displayName" | "destinationAccountId" | "status" | "createdAt" | "updatedAt", Known<AccountSchemas["BeneficiaryResponse"], {
  currency: "USD" | "EUR" | "GBP" | "INR"
}>>;

export type LedgerAccountProjection = FromApi<TransactionSchemas["LedgerAccountSummaryResponse"], "externalAccountId" | "currency" | "postedBalance" | "pendingBalance" | "availableBalance" | "projectionVersion">;

export type CustomerJournalPosting = FromApi<TransactionSchemas["CustomerJournalPostingResponse"], "externalAccountId" | "amount" | "currency", Known<TransactionSchemas["CustomerJournalPostingResponse"], {
  direction: "DEBIT" | "CREDIT" | string
}>>;

export type CustomerJournal = FromApi<TransactionSchemas["CustomerJournalResponse"], "journalId" | "journalType" | "state" | "currency" | "customerAmount", Known<TransactionSchemas["CustomerJournalResponse"], {
  postings: CustomerJournalPosting[]
}>>;

export type NotificationType = NonNullable<AccountSchemas["Notification"]["type"]>;
export type NotificationSeverity = NonNullable<AccountSchemas["Notification"]["severity"]>;
export type NotificationStatus = NonNullable<AccountSchemas["Notification"]["status"]>;
export type NotificationSourceType = NonNullable<AccountSchemas["Notification"]["sourceType"]>;

export type Notification = FromApi<AccountSchemas["Notification"], "notificationId" | "userId" | "type" | "severity" | "status" | "title" | "message" | "sourceType" | "sourceId" | "dedupeKey" | "createdAt">;

export type NotificationSummary = FromApi<AccountSchemas["NotificationSummaryResponse"], "total" | "unread", Known<AccountSchemas["NotificationSummaryResponse"], {
  bySeverity: Partial<Record<NotificationSeverity, number>>,
  byType: Partial<Record<NotificationType, number>>,
  bySourceType: Partial<Record<NotificationSourceType, number>>
}>>;

export type TransactionType = "DEPOSIT" | "WITHDRAWAL" | "TRANSFER" | "REVERSAL" | "REFUND" | string;
export type TransactionStatus = "COMPLETED" | "PENDING" | "FAILED" | "REVERSED" | string;
export type DisputeStatus = NonNullable<TransactionSchemas["TransactionDisputeResponse"]["status"]>;
export type DisputeReasonCode = NonNullable<TransactionSchemas["TransactionDisputeResponse"]["reasonCode"]>;

export type Transaction = FromApi<TransactionSchemas["TransactionResponse"], "transactionId" | "amount" | "currency" | "createdAt", Known<TransactionSchemas["TransactionResponse"], {
  type: TransactionType,
  status: TransactionStatus
}>>;

export type MfaStatus = FromApi<AccountSchemas["StatusResponse"], "enrolled" | "status" | "recoveryCodesRemaining">;

export type MfaEnrollment = FromApi<AccountSchemas["EnrollmentResponse"], "secret" | "otpauthUri">;
export type MfaConfirmation = FromApi<AccountSchemas["ConfirmationResponse"], "active" | "recoveryCodes">;
export type ChallengeVerification = FromApi<AccountSchemas["ChallengeVerificationResponse"], "challengeId" | "proof" | "proofExpiresAt">;
export type SpendingLimit = FromApi<AccountSchemas["LimitResponse"], "accountId" | "currency" | "transferDailyLimit" | "withdrawalDailyLimit" | "transferUsedToday" | "withdrawalUsedToday">;

export type TransactionStats = FromApi<TransactionSchemas["TransactionStatsResponse"], never, Known<TransactionSchemas["TransactionStatsResponse"], {
  transactionCountsByType?: Record<string, number>,
  transactionAmountsByType?: Record<string, number>
}>>;


export type ScheduledTransferStatus = NonNullable<TransactionSchemas["ScheduledTransferResponse"]["status"]>;
export type ScheduledTransferType = NonNullable<TransactionSchemas["ScheduledTransferResponse"]["scheduleType"]>;
export type ScheduledTransferFrequency = NonNullable<TransactionSchemas["ScheduledTransferResponse"]["frequency"]>;
export type ScheduledTransferRunStatus = NonNullable<TransactionSchemas["ScheduledTransferRunResponse"]["status"]>;

export type ScheduledTransfer = FromApi<TransactionSchemas["ScheduledTransferResponse"], "scheduleId" | "userId" | "fromAccountId" | "toAccountId" | "amount" | "currency" | "scheduleType" | "nextRunAt" | "timeZone" | "sourceLocalDateTime" | "nextRunLocalDateTime" | "status" | "version", Known<TransactionSchemas["ScheduledTransferResponse"], {
  dstOverlapPolicy: "EARLIER" | "LATER",
  dstGapPolicy: "SHIFT_FORWARD" | "REJECT"
}>>;

export type ScheduledTransferRun = FromApi<TransactionSchemas["ScheduledTransferRunResponse"], "runId" | "scheduleId" | "scheduledFor" | "startedAt" | "status" | "idempotencyKey">;

export type OutcomeAssumptionType = NonNullable<TransactionSchemas["AssumptionInput"]["type"]>;
export type OutcomeShockType = NonNullable<TransactionSchemas["ShockInput"]["type"]>;

export type OutcomeAssumption = FromApi<TransactionSchemas["AssumptionInput"], "id" | "date" | "amount" | "type" | "label" | "flexible" | "critical">;

export type OutcomeShock = FromApi<TransactionSchemas["ShockInput"], "id" | "type" | "targetAssumptionId" | "label">;

export type OutcomeScenarioRequest = FromApi<TransactionSchemas["ScenarioRequest"], "name" | "accountIds" | "currency" | "timeZone" | "horizonStart" | "horizonDays" | "protectedMinimum", Known<TransactionSchemas["ScenarioRequest"], {
  assumptions: OutcomeAssumption[],
  shocks: OutcomeShock[],
  outcomeType?: "BALANCE_FLOOR" | "SCHEDULED_OBLIGATION"
}>>;

export type OutcomeTimelineEvent = FromApi<TransactionSchemas["TimelineEvent"], "eventId" | "date" | "amount" | "label" | "flexible" | "critical", Known<TransactionSchemas["TimelineEvent"], {
  source: "ASSUMPTION" | "SCHEDULED_TRANSFER" | string
}>>;

export type OutcomeTimelineDay = FromApi<TransactionSchemas["TimelineDay"], "date" | "openingBalance" | "closingBalance", Known<TransactionSchemas["TimelineDay"], {
  events: OutcomeTimelineEvent[]
}>>;

export type OutcomeForecast = FromApi<TransactionSchemas["ForecastProof"], "safe" | "startingBalance" | "protectedMinimum" | "lowestBalance" | "closingBalance" | "balanceFloorSatisfied" | "protectedObligationSatisfied", Known<TransactionSchemas["ForecastProof"], {
  triggeringEvents: OutcomeTimelineEvent[],
  timeline: OutcomeTimelineDay[],
  invariantBreaches: Array<{
    type: "BALANCE_FLOOR_BREACH" | "PROTECTED_OBLIGATION_INSUFFICIENT_FUNDS" | "PROTECTED_OBLIGATION_MISSING_OR_CHANGED" | string;
    date: string;
    eventId?: string;
    scheduleId?: string;
    balanceBefore?: number;
    requiredAmount?: number;
    shortfall?: number;
    explanation: string;
  }>
}>>;

export type OutcomeRepairAction = FromApi<TransactionSchemas["RepairAction"], "actionId" | "amount" | "affectedEventIds" | "explanation" | "disruptionScore" | "previewOnly", Known<TransactionSchemas["RepairAction"], {
  type: "RESERVE_BUFFER" | "SHIFT_OPTIONAL_SCHEDULE" | "REDUCE_OPTIONAL_SCHEDULE" | "TEMPORARY_SPENDING_LIMIT" | "REVIEW_FLEXIBLE_EXPENSES" | string
}>>;

export type OutcomeRepairAlternative = FromApi<TransactionSchemas["RepairAlternative"], "rank" | "alternativeId" | "certificateHash" | "explanation", Known<TransactionSchemas["RepairAlternative"], {
  actions: OutcomeRepairAction[],
  replay: OutcomeForecast,
  rankingFactors: {
    restoresAllInvariants: boolean;
    actionCount: number;
    disruptionScore: number;
    moneyMovedOrDeferred: number;
    stableActionIds: string[];
  }
}>>;
export type OutcomeSimulation = FromApi<TransactionSchemas["SimulationProof"], "evaluatedCombinations" | "searchCapped", Known<TransactionSchemas["SimulationProof"], {
  baseline: OutcomeForecast,
  reverseStress: {
    failureFound: boolean;
    baselineFailure: boolean;
    minimalShockCount?: number;
    appliedShocks: Array<{ shockId: string; type: OutcomeShockType; label: string; targetAssumptionId: string; severityScore: number }>;
    failureDate?: string;
    lowestBalance?: number;
    triggeringEvents: OutcomeTimelineEvent[];
    timeline: OutcomeTimelineDay[];
    minimalityExplanation: string;
  },
  repair: {
    maximumShortfall: number;
    selectedRepairs: OutcomeRepairAction[];
    verifiedInModel: boolean;
    minimalityExplanation: string;
    alternatives: OutcomeRepairAlternative[];
    rejectedCandidates: Array<{ candidateId: string; type: string; targetId?: string; reasonCode: string; explanation: string }>;
    evaluatedCombinations: number;
    searchCapped: boolean;
    maxCombinationSize: number;
    maxEvaluatedCombinations: number;
    engineVersion: string;
    certificateHash: string;
  }
}>>;

export type OutcomeNotificationDelivery = FromApi<TransactionSchemas["NotificationDeliveryEvidence"], "deliveryId" | "attemptCount" | "dedupeKey", Known<TransactionSchemas["NotificationDeliveryEvidence"], {
  state: "PENDING" | "RETRY_SCHEDULED" | "DELIVERED" | "TERMINAL_FAILED"
}>>;

export type OutcomeGuardrailControl = FromApi<TransactionSchemas["GuardrailControlResponse"], "executionEnabled" | "reason" | "changedBy" | "updatedAt">;

export type OutcomeGuardrailOperatorPolicy = FromApi<TransactionSchemas["GuardrailOperatorPolicyResponse"], "userId" | "scenarioId", Known<TransactionSchemas["GuardrailOperatorPolicyResponse"], {
  policy: OutcomeGuardrailPolicy
}>>;

export type OutcomeGuardrailControlEvent = FromApi<TransactionSchemas["GuardrailControlEventResponse"], "eventId" | "executionEnabled" | "reason" | "actor" | "createdAt">;

export type OutcomeGuardrailTerms = FromApi<TransactionSchemas["GuardrailTermsResponse"], "version" | "hash" | "title" | "summary" | "confirmations", Known<TransactionSchemas["GuardrailTermsResponse"], {
  backgroundExecution: false
}>>;

export type OutcomeGuardrailPolicy = FromApi<TransactionSchemas["GuardrailPolicyResponse"], "policyId" | "guardrailId" | "fundingAccountId" | "protectedAccountId" | "currency" | "triggerThreshold" | "maxActionAmount" | "totalLimit" | "totalExecuted" | "totalReserved" | "maxExecutions" | "executionCount" | "termsVersion" | "termsHash" | "expiresAt" | "consentedAt" | "activationChallengeId" | "activationChallengeExpiresAt" | "executionEnabled" | "executionControlReason" | "requiresReconsent", Known<TransactionSchemas["GuardrailPolicyResponse"], {
  status: "CONSENT_PENDING" | "ACTIVE" | "SUSPENDED" | "REVOKED" | "EXPIRED",
  effectiveStatus: "CONSENT_PENDING" | "ACTIVE" | "SUSPENDED" | "REVOKED" | "EXPIRED",
  notificationDelivery?: OutcomeNotificationDelivery
}>>;

export type OutcomeGuardrailExecution = FromApi<TransactionSchemas["GuardrailExecutionResponse"], "executionId" | "guardrailId" | "policyId" | "amount" | "currency" | "authorizationRequired" | "createdAt", Known<TransactionSchemas["GuardrailExecutionResponse"], {
  status: "REQUESTED" | "AWAITING_AUTHORIZATION" | "COMPLETED" | "CANCELLED" | "FAILED",
  notificationDelivery?: OutcomeNotificationDelivery
}>>;

export type OutcomeGuardrail = FromApi<TransactionSchemas["GuardrailResponse"], "guardrailId" | "type" | "thresholdAmount" | "currency" | "accountIds" | "expiresAt" | "previewText", Known<TransactionSchemas["GuardrailResponse"], {
  status: "DRAFT" | "ACCEPTED" | "EXPIRED",
  policy?: OutcomeGuardrailPolicy,
  candidateActions: OutcomeRepairAction[],
  rankingFactors?: OutcomeRepairAlternative["rankingFactors"]
}>>;

export type OutcomeScenarioSummary = FromApi<TransactionSchemas["ScenarioSummary"], "scenarioId" | "name" | "version" | "status" | "currency" | "horizonStart" | "horizonDays" | "protectedMinimum" | "baselineSafe" | "updatedAt", Known<TransactionSchemas["ScenarioSummary"], {
  outcomeType?: "BALANCE_FLOOR" | "SCHEDULED_OBLIGATION"
}>>;

export type OutcomeFxQuote = FromApi<TransactionSchemas["FxRateQuote"], "quoteCurrency" | "baseCurrency" | "rate" | "asOf" | "provider" | "provenance" | "stale", Known<TransactionSchemas["FxRateQuote"], {
  stalenessPolicy: "REJECT" | "WARN"
}>>;
export type OutcomeScenario = OutcomeScenarioSummary & {
  timeZone: string;
  accountIds: string[];
  assumptions: OutcomeAssumption[];
  shocks: OutcomeShock[];
  sourceSnapshot: {
    startingAvailableBalance: number;
    baseCurrency: string;
    ledgerAccounts: Array<{ accountId: string; currency: string; availableBalance: number; projectionVersion: number; capturedAt: string; baseAvailableBalance: number; baseCurrency: string; fxQuote?: OutcomeFxQuote }>;
    scheduledCashflows: Array<{ eventId: string; scheduleId: string; scheduledFor: string; date: string; amount: number; currency: string; status: string; cadence: string; evaluationTimeZone: string; label: string; fromAccountId: string; toAccountId: string; sourceAmount: number; sourceCurrency: string; fxQuote?: OutcomeFxQuote; scheduleVersion: number; scheduleOwnerId: string; sourceTimeZone: string; dueLocalDate: string; sourceOwnedByCustomer: boolean; destinationOwnedByCustomer: boolean; repairEligible: boolean; repairIneligibilityReason?: string }>;
    protectedObligation?: { scheduleId: string; scheduleVersion: number; status: string; ownerId: string; fromAccountId: string; toAccountId: string; sourceOwnedByCustomer: boolean; destinationOwnedByCustomer: boolean; amount: number; currency: string; scheduleType: string; cadence: string; dueAt: string; dueLocalDate: string; sourceTimeZone: string; evaluationTimeZone: string; endAt?: string; sourceProjectionVersion: number; capturedAt: string; valid: boolean; invalidReason?: string };
    fxQuotes: OutcomeFxQuote[];
    executableFx: false;
    sourceFingerprint: string;
  };
  simulation: OutcomeSimulation;
  guardrails: OutcomeGuardrail[];
  createdAt: string;
  outcomeType: "BALANCE_FLOOR" | "SCHEDULED_OBLIGATION";
  protectedScheduleId?: string;
  protectedScheduleVersion?: number;
  monitoring?: OutcomeMonitoringHealth;
};

export type OutcomeMonitoringHealth = FromApi<TransactionSchemas["MonitoringHealth"], "consecutiveFailures">;

export type OutcomeDivergence = FromApi<TransactionSchemas["DivergenceResponse"], "scenarioId" | "previousSourceFingerprint" | "currentSourceFingerprint" | "diverged" | "protectionAtRisk" | "notificationEmitted" | "checkedAt" | "evaluationEventId" | "warningAcknowledged", Known<TransactionSchemas["DivergenceResponse"], {
  freshSimulation: OutcomeSimulation,
  freshSourceSnapshot?: OutcomeScenario["sourceSnapshot"],
  notificationDelivery?: { deliveryId: string; state: "PENDING" | "RETRY_SCHEDULED" | "DELIVERED" | "TERMINAL_FAILED"; attemptCount: number; nextAttemptAt: string; deliveredAt?: string; terminalAt?: string; slaEscalatedAt?: string; lastError?: string; dedupeKey: string }
}>>;

export type AuditLogEntry = FromApi<TransactionSchemas["AuditLogEntryResponse"], "eventId" | "eventType" | "action" | "outcome" | "createdAt">;

export type AuditSummary = FromApi<TransactionSchemas["AuditSummaryResponse"], "totalEvents" | "failureEvents" | "reversalEvents" | "securityEvents">;

export type TransactionDisputeNote = FromApi<TransactionSchemas["Note"], "noteId" | "author" | "note" | "createdAt">;

export type TransactionDispute = FromApi<TransactionSchemas["TransactionDisputeResponse"], "disputeId" | "disputeNumber" | "transactionId" | "userId" | "status" | "reasonCode" | "description" | "createdBy" | "createdAt", Known<TransactionSchemas["TransactionDisputeResponse"], {
  notes?: TransactionDisputeNote[]
}>>;

export type DisputeSummary = FromApi<TransactionSchemas["DisputeSummaryResponse"], "totalDisputes" | "openDisputes" | "inReviewDisputes" | "approvedDisputes" | "deniedDisputes" | "closedDisputes" | "unassignedDisputes">;

export type RiskAlertStatus = NonNullable<TransactionSchemas["RiskAlertResponse"]["status"]>;
export type RiskAlertSeverity = NonNullable<TransactionSchemas["RiskAlertResponse"]["severity"]>;
export type RiskAlertType = NonNullable<TransactionSchemas["RiskAlertResponse"]["alertType"]>;

export type RiskAlert = FromApi<TransactionSchemas["RiskAlertResponse"], "alertId" | "alertType" | "severity" | "status" | "reason" | "createdAt">;

export type RiskSummary = FromApi<TransactionSchemas["RiskSummaryResponse"], "totalAlerts" | "openAlerts" | "highSeverityAlerts" | "escalatedAlerts">;

export type RiskCaseStatus = NonNullable<TransactionSchemas["RiskCaseResponse"]["status"]>;
export type RiskCasePriority = NonNullable<TransactionSchemas["RiskCaseResponse"]["priority"]>;

export type RiskCaseNote = FromApi<TransactionSchemas["Note"], "noteId" | "author" | "note" | "createdAt">;

export type RiskCase = FromApi<TransactionSchemas["RiskCaseResponse"], "caseId" | "caseNumber" | "status" | "priority" | "title" | "createdBy" | "createdAt", Known<TransactionSchemas["RiskCaseResponse"], {
  linkedAlerts?: RiskAlert[],
  notes?: RiskCaseNote[]
}>>;

export type RiskCaseSummary = FromApi<TransactionSchemas["RiskCaseSummaryResponse"], "totalCases" | "openCases" | "inReviewCases" | "resolvedCases" | "closedCases" | "unassignedCases">;

export type InvestigationItemType = "TRANSACTION" | "AUDIT_EVENT" | "RISK_ALERT" | "RISK_CASE" | "CASE_NOTE" | "DISPUTE" | "DISPUTE_NOTE";

export type InvestigationTimelineItem = FromApi<TransactionSchemas["InvestigationTimelineItemResponse"], "itemId" | "title" | "createdAt", Known<TransactionSchemas["InvestigationTimelineItemResponse"], {
  itemType: InvestigationItemType,
  metadata?: Record<string, unknown>
}>>;

export type InvestigationSummary = FromApi<TransactionSchemas["InvestigationSummaryResponse"], "transactions" | "auditEvents" | "riskAlerts" | "riskCases" | "failures" | "reversals" | "highSeverityItems">;

export type ReconciliationRunStatus = "RUNNING" | "COMPLETED" | "COMPLETED_WITH_EXCEPTIONS" | "FAILED";
export type ReconciliationExceptionStatus = "OPEN" | "ACKNOWLEDGED" | "IN_PROGRESS" | "RESOLVED" | "WAIVED";
export type ReconciliationSeverity = "INFO" | "WARNING" | "HIGH" | "CRITICAL";

export type ReconciliationRun = FromApi<TransactionSchemas["ReconciliationRunResponse"], "runId" | "businessDate" | "startedAt" | "totalExceptions" | "criticalExceptions", Known<TransactionSchemas["ReconciliationRunResponse"], {
  status: ReconciliationRunStatus | string
}>>;

// The API has no title, description or resolvedAt/resolvedBy; summary and resolutionNote carry that.
export type ReconciliationException = FromApi<TransactionSchemas["ReconciliationExceptionResponse"], "exceptionId" | "checkCode" | "fingerprint" | "detectedAt" | "version", Known<TransactionSchemas["ReconciliationExceptionResponse"], {
  severity: ReconciliationSeverity | string,
  status: ReconciliationExceptionStatus | string,
  notes?: ReconciliationExceptionNote[]
}>>;

export type ReconciliationExceptionNote = FromApi<TransactionSchemas["ReconciliationExceptionNoteResponse"], "noteId" | "author" | "note">;

export type CustomerStatementLine = FromApi<TransactionSchemas["CustomerStatementLineResponse"], "lineId" | "journalId" | "lineSequence" | "effectiveDate" | "amount" | "runningBalance" | "currency">;

export type CustomerStatement = FromApi<TransactionSchemas["CustomerStatementResponse"], "statementId" | "externalAccountId" | "currency" | "periodStart" | "periodEnd" | "statementVersion" | "openingBalance" | "closingBalance" | "generatedAt", Known<TransactionSchemas["CustomerStatementResponse"], {
  lines: CustomerStatementLine[]
}>>;
